# Generated by Django 4.1.7 on 2023-08-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_rename_subject_contact_message_alter_contact_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
