# Generated by Django 4.1.7 on 2023-08-18 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
